apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: <YOUR_ECR_CATALOG_IMAGE>
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: <YOUR-RDS-ENDPOINT>
        - name: DB_USER
          value: postgres
        - name: DB_NAME
          value: postgres
        - name: DB_PASS
          value: <YOUR-RDS-PASSWORD>
        - name: DB_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: LoadBalancer
  selector:
    app: auth-service
  ports:
  - port: 3000
    targetPort: 3000
