apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
      - name: catalog-service
        image: <tu_ecr_catalog_image>
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: <tu-rds-endpoint>
        - name: DB_USER
          value: postgres
        - name: DB_NAME
          value: postgres
        - name: DB_PASS
          value: testing
        - name: DB_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  type: LoadBalancer
  selector:
    app: catalog-service
  ports:
  - port: 3000
    targetPort: 3000
